// DO NOT EDIT. This file is generated by fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $0 from "./routes/_404.tsx";
import * as $1 from "./routes/_500.tsx";
import * as $2 from "./routes/api/joke.ts";
import * as $3 from "./routes/beverages.tsx";
import * as $4 from "./routes/beverages/[beverageId].tsx";
import * as $5 from "./routes/index.tsx";
import * as $$0 from "./islands/Carousel.tsx";
import * as $$1 from "./islands/Counter.tsx";

const manifest = {
  routes: {
    "./routes/_404.tsx": $0,
    "./routes/_500.tsx": $1,
    "./routes/api/joke.ts": $2,
    "./routes/beverages.tsx": $3,
    "./routes/beverages/[beverageId].tsx": $4,
    "./routes/index.tsx": $5,
  },
  islands: {
    "./islands/Carousel.tsx": $$0,
    "./islands/Counter.tsx": $$1,
  },
  baseUrl: import.meta.url,
};

export default manifest;
